//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeLog
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<System.DateTime> ChangeDateCreated { get; set; }
        public string ChangePerformed { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
