//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTypeFacilityAccessible
    {
        public int Id { get; set; }
        public int EmployeeTypeId { get; set; }
        public int FacilityId { get; set; }
        public bool IsAccessible { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Facility Facility { get; set; }
    }
}
