//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
            this.EmployeeTypeFacilityAccessibles = new HashSet<EmployeeTypeFacilityAccessible>();
        }
    
        public int Id { get; set; }
        public string EmployeeTypeName { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<EmployeeTypeFacilityAccessible> EmployeeTypeFacilityAccessibles { get; set; }
    }
}
