//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.ChangeLogs = new HashSet<ChangeLog>();
            this.EmployeeTypeFacilityAccessibles = new HashSet<EmployeeTypeFacilityAccessible>();
            this.FacilityPeriods = new HashSet<FacilityPeriod>();
        }
    
        public int Id { get; set; }
        public string FacilityName { get; set; }
    
        public virtual ICollection<ChangeLog> ChangeLogs { get; set; }
        public virtual ICollection<EmployeeTypeFacilityAccessible> EmployeeTypeFacilityAccessibles { get; set; }
        public virtual ICollection<FacilityPeriod> FacilityPeriods { get; set; }
    }
}
