//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolPeriod
    {
        public SchoolPeriod()
        {
            this.FacilityPeriods = new HashSet<FacilityPeriod>();
        }
    
        public int Id { get; set; }
        public string SchoolYear { get; set; }
        public int SHSTerm { get; set; }
        public Nullable<System.DateTime> SHSTermStartingDate { get; set; }
        public Nullable<System.DateTime> SHSTermEndingDate { get; set; }
        public bool IsPeriodActive { get; set; }
    
        public virtual ICollection<FacilityPeriod> FacilityPeriods { get; set; }
    }
}
