//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaintenanceWebUtilityWebForm2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHS_School_Period
    {
        public int Period_ID { get; set; }
        public int SHS_Term_Code { get; set; }
        public byte Period_Number { get; set; }
        public string Period_Description { get; set; }
        public double School_Days { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime Encoding_Start { get; set; }
        public System.DateTime Encoding_End { get; set; }
        public System.DateTime Updated_Date { get; set; }
        public string Updated_By { get; set; }
        public string Updated_Host { get; set; }
        public string Updated_App { get; set; }
    
        public virtual SHS_School_Term SHS_School_Term { get; set; }
    }
}
